In [8]:
import sys
import numpy as np

def read_file(text_path):
    _tmp = []
    with open(text_path, 'r', encoding="utf-8") as f:
        for line in f:
            line = line.split()
            _tmp.append(line)
    return np.array(_tmp).astype(float)

def find_order_of_chain(lines):
    atom_dic = {}
    beginning = {}

    # calculate the distance, 
    # and fit the atom index whoes distance between 3.7 and 3.8
    for i in range(len(lines)):
        _tmp = []
        _tmp2 = []
        for j in range(len(lines)):
            print(lines[i][1:])
            print(lines[j][1:])

            _distance = np.sqrt(np.sum( (lines[i][1:]-lines[j][1:])**2 ))

            print(_distance)

            _tmp2.append(_distance)
            if (_distance<3.9) and (_distance>3.7):
                _tmp.append(lines[j][0])

        atom_dic[lines[i][0]] = _tmp
        beginning[lines[i][0]] = _tmp2

    return beginning


In [9]:
text_path = './test_q1.txt'
lines = read_file(text_path)
find_order_of_chain(lines)

[13.257 10.745 15.081]
[13.257 10.745 15.081]
0.0
[13.257 10.745 15.081]
[13.512  5.395 12.878]
5.79143626400222
[13.257 10.745 15.081]
[13.564 11.573 18.836]
3.8574418984606877
[13.257 10.745 15.081]
[15.445  7.667 15.246]
3.7800334654603254
[13.257 10.745 15.081]
[17.334 10.956 18.691]
5.449637602630105
[13.257 10.745 15.081]
[17.924 13.421 15.877]
5.438334395750228
[13.257 10.745 15.081]
[18.504 12.312 12.298]
6.142604252269555
[13.257 10.745 15.081]
[21.452 16.969  6.513]
13.39054983934566
[13.257 10.745 15.081]
[21.936 12.911 10.809]
9.912950166322839
[13.257 10.745 15.081]
[22.019 13.242  7.02 ]
12.165006124125052
[13.512  5.395 12.878]
[13.257 10.745 15.081]
5.79143626400222
[13.512  5.395 12.878]
[13.512  5.395 12.878]
0.0
[13.512  5.395 12.878]
[13.564 11.573 18.836]
8.583015320969665
[13.512  5.395 12.878]
[15.445  7.667 15.246]
3.808660788256156
[13.512  5.395 12.878]
[17.334 10.956 18.691]
8.906367048353665
[13.512  5.395 12.878]
[17.924 13.421 15.877]
9.637241358397121
[13

{1.0: [0.0,
  5.79143626400222,
  3.8574418984606877,
  3.7800334654603254,
  5.449637602630105,
  5.438334395750228,
  6.142604252269555,
  13.39054983934566,
  9.912950166322839,
  12.165006124125052],
 2.0: [5.79143626400222,
  0.0,
  8.583015320969665,
  3.808660788256156,
  8.906367048353665,
  9.637241358397121,
  8.549932923713495,
  15.411498986146677,
  11.477577836808601,
  12.971531212620969],
 3.0: [3.8574418984606877,
  8.583015320969665,
  0.0,
  5.628774022822376,
  3.822906485908333,
  5.583939917298536,
  8.227707153271803,
  15.594668608213514,
  11.675331130207828,
  14.624993743588403],
 4.0: [3.7800334654603254,
  3.808660788256156,
  5.628774022822376,
  0.0,
  5.123852749640644,
  6.29699277433284,
  6.294776405878132,
  14.10235944797891,
  9.450903977927192,
  11.914914057600248],
 5.0: [5.449637602630105,
  8.906367048353665,
  3.822906485908333,
  5.123852749640644,
  0.0,
  3.787204905995976,
  6.639132850003831,
  14.192173089417984,
  9.334149827381173,
  